import { defineConfig } from 'vitepress'
import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath, URL } from 'node:url'

// The API reference sidebar is generated by `npm run docs:api` (typedoc-vitepress-theme).
// Guard the read so `vitepress dev` still boots if the API hasn't been generated yet.
const apiSidebarPath = fileURLToPath(new URL('../api/typedoc-sidebar.json', import.meta.url))
const apiSidebar = existsSync(apiSidebarPath)
  ? JSON.parse(readFileSync(apiSidebarPath, 'utf-8'))
  : [{ text: 'Run `npm run docs:api` to generate the API reference', link: '/api/' }]

export default defineConfig({
  base: '/bigdecimal.js/',
  title: 'BigDecimal.js',
  description:
    'Arbitrary-precision decimals for JavaScript & TypeScript, built on native BigInt. A faithful port of Java\'s BigDecimal — fast, exact, zero dependencies.',
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,
  // Legacy versioned TypeDoc archives (migrated from the gh-pages branch) live at
  // /api/<version>/docs/ and are injected into the build by CI, so they don't exist
  // during a local `vitepress build`. Skip dead-link checking for those paths only.
  ignoreDeadLinks: [/^\/api\/\d/],

  head: [
    ['link', { rel: 'icon', href: '/bigdecimal.js/favicon.svg', type: 'image/svg+xml' }],
    ['meta', { name: 'theme-color', content: '#c026d3' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'BigDecimal.js' }],
    ['meta', { property: 'og:description', content: 'Arbitrary-precision decimals for JS/TS on native BigInt. Fast, exact, zero-dependency.' }],
    ['meta', { property: 'og:url', content: 'https://srknzl.github.io/bigdecimal.js/' }],
    ['meta', { name: 'twitter:card', content: 'summary' }],
  ],

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'BigDecimal.js',

    nav: [
      { text: 'Guide', link: '/guide/getting-started', activeMatch: '/guide/' },
      { text: 'Cookbook', link: '/cookbook/avoiding-float-errors', activeMatch: '/cookbook/' },
      { text: 'Migration', link: '/migration/from-decimal-js', activeMatch: '/migration/' },
      { text: 'API', link: '/api/', activeMatch: '/api/' },
      { text: 'Playground', link: '/playground' },
      {
        text: 'v1.7.0',
        items: [
          {
            text: 'This release',
            items: [
              { text: 'Changelog', link: 'https://github.com/srknzl/bigdecimal.js/blob/main/CHANGELOG.md' },
              { text: 'API Reference', link: '/api/' },
              { text: 'npm', link: 'https://www.npmjs.com/package/bigdecimal.js' },
            ],
          },
          {
            // Full https URLs (not /api/... paths): these archives are injected at deploy
            // time and aren't VitePress routes, so an absolute URL makes the client router
            // do a real navigation instead of a SPA route lookup that 404s.
            text: 'Older versions',
            items: [
              { text: 'v1.6.2', link: 'https://srknzl.github.io/bigdecimal.js/api/1.6.2/docs/' },
              { text: 'v1.6.1', link: 'https://srknzl.github.io/bigdecimal.js/api/1.6.1/docs/' },
              { text: 'v1.6.0', link: 'https://srknzl.github.io/bigdecimal.js/api/1.6.0/docs/' },
              { text: 'All versions →', link: '/versions' },
            ],
          },
        ],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Core Concepts', link: '/guide/core-concepts' },
            { text: 'Performance', link: '/guide/performance' },
          ],
        },
        {
          text: 'Working with values',
          items: [
            { text: 'Formatting Output', link: '/guide/formatting' },
            { text: 'Lossless JSON', link: '/guide/lossless-json' },
            { text: 'Error Handling', link: '/guide/error-handling' },
          ],
        },
        { text: 'Try it live', items: [{ text: 'Playground', link: '/playground' }] },
      ],
      '/cookbook/': [
        {
          text: 'Cookbook',
          items: [
            { text: 'Avoiding Float Errors', link: '/cookbook/avoiding-float-errors' },
            { text: 'Money & Currency', link: '/cookbook/money-currency' },
            { text: 'Rounding Modes', link: '/cookbook/rounding' },
            { text: 'Percentages & Tax', link: '/cookbook/percentages-tax' },
          ],
        },
      ],
      '/migration/': [
        {
          text: 'Migrating to BigDecimal.js',
          items: [
            { text: 'From decimal.js', link: '/migration/from-decimal-js' },
            { text: 'From bignumber.js', link: '/migration/from-bignumber-js' },
            { text: 'From big.js', link: '/migration/from-big-js' },
            { text: 'From Java BigDecimal', link: '/migration/from-java' },
          ],
        },
      ],
      '/api/': [{ text: 'API Reference', items: apiSidebar }],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/srknzl/bigdecimal.js' }],

    // Show h2 *and* h3 in the right-hand outline so individual methods (### add())
    // appear under the class pages, not just the "Methods"/"Properties" sections.
    outline: { level: [2, 3], label: 'On this page' },

    search: { provider: 'local' },

    editLink: {
      pattern: 'https://github.com/srknzl/bigdecimal.js/edit/main/website/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Released under the GPL-2.0-only WITH Classpath-exception-2.0 License.',
      copyright: 'Copyright © 2021–present Serkan Özel',
    },
  },

  markdown: {
    // A ```js-live fenced block renders as an interactive <Playground> instead of a
    // static code block. HTML-escaping the content sidesteps all attribute-quoting
    // pitfalls, so blank lines and quotes inside the code are fine.
    config(md) {
      const defaultFence = md.renderer.rules.fence!
      md.renderer.rules.fence = (tokens, idx, options, env, self) => {
        const info = tokens[idx].info.trim()
        if (info === 'js-live' || info === 'ts-live') {
          const code = md.utils.escapeHtml(tokens[idx].content.replace(/\n$/, ''))
          return `<Playground code="${code}" />\n`
        }
        return defaultFence(tokens, idx, options, env, self)
      }
    },
  },

  vite: {
    resolve: {
      alias: {
        // The Playground imports the exact locally-built ESM bundle, so the site
        // always demonstrates this repo's code (not the published npm version).
        'bigdecimal.js': fileURLToPath(new URL('../../lib/bigdecimal.mjs', import.meta.url)),
      },
    },
  },
})
