name: CI tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install
        run: |
          npm i
      - name: Lint
        run: |
          npm run lint:ci
      - name: Compile
        run: |
          npm run compile
      - name: Tests
        run: |
          npm run coverage
      - name: Publish to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
