name: CI tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install
        run: |
          npm i
      - name: Lint
        run: |
          npm run lint:ci
      - name: Compile
        run: |
          npm run compile
      - name: Tests
        run: |
          npm run test
